categories:
  - title: '🚀 Features'
    label: 'feature'
  - title: '🐞 Bug Fixes'
    collapse-after: 5
    label: 'bug'
  - title: '🧰 Maintenance'
    collapse-after: 5
    label: 'chore'
change-template: '- $TITLE by @$AUTHOR (#$NUMBER)'
autolabeler:
  - label: 'feature'
    branch:
      - '/feat.+/i'
  - label: 'bug'
    branch:
      - '/fix.+/i'
replacers:
  - search: '/feature:\s*/i'
    replace: ''
  - search: '/bug:\s*/i'
    replace: 'Fixed '
exclude-labels:
  - "release"
header: |
  <img src="./.github/resources/banner-release-universal" width="100%">
  <br />
  <br />
template: |
  ## What's new?

  $CHANGES