categories:
  - title: '🚀 Features'
    label: 'feature'
  - title: '🐞 Bug Fixes'
    collapse-after: 5
    label: 'bug'
  - title: '🧰 Maintenance'
    collapse-after: 5
    labels: 
      - 'chore'
      - 'doc'
change-template: '- $TITLE by @$AUTHOR (#$NUMBER)'
autolabeler:
  - label: 'feature'
    branch:
      - '/feat.+/i'
  - label: 'bug'
    branch:
      - '/fix.+/i'
  - label: 'chore'
    branch:
      - '/chore.+/i'
      - '/doc.+/i'
replacers:
  - search: '/(feature:|bug:)\s*/i'
    replace: ''
exclude-labels:
  - "release"
header: |
  <img src="/.github/resources/banner-release-universal.png" width="100%">
template: |
  # What's new?

  $CHANGES