name: 'Release Drafter'

on:
  workflow_call:

jobs:
  create_release_draft:
    name: Create Release Draft
    runs-on: ubuntu-latest
    steps:
      - name: Download DMG
        uses: actions/download-artifact@v3
        with:
          name: mupl
      
      - name: Prepare Release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          files: mupl.dmg
          draft: true
          repo_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate Release Notes
        uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}