name: 'Release'

on:
  push:
    branches:
      - master

jobs:
  update_tag:
    if: contains(github.event.head_commit.message, 'release:')
    name: Update Tag
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Update tag
        run: |
          VERSION=$(echo -n $(echo "${{ github.event.head_commit.message }}" | grep -Eo "[0-9]+\.[0-9]+\.[0-9]+" | head -1))
          git tag -f $VERSION ${{ github.sha }}
          git push -f --tags
  package:
    needs: update_tag
    name: Package
    uses: ./.github/workflows/package.yml
    secrets: inherit
  draft_release:
    needs: package
    name: Draft Release
    uses: ./.github/workflows/create-release-draft.yml
    with:
      tag: ${{ needs.package.outputs.app_version }}
    secrets: inherit